import { Metadata } from "next"

interface CategoryProps {
    params: {
      category: string
    }
  }
  export const metadata: Metadata = {
    title: 'Page',
    description: 'Generated by create next app',
  }
  
  
  export default function Category(props: CategoryProps){
    const { category } = props.params
    return(
      <h1>Categoria dinámica: {category}</h1>
    )
  }